name: New Changes

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print Working Directory
        run: pwd

      - name: List Files
        run: ls

      - name: Show Index File
        run: cat index.js