name: "New CHnages"

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v4
      - run: pwd
      - run: ls
      - name: runIndex
      - run: cat index.js